### ISSUE TITLE
No tag for version 0.7.0

### ISSUE THREAD

**Issue by PierreRust** [powerapi-ng/smartwatts-formula#11]
Since commit fde7f78ad0b4e0dc7eb28bac278fc3fd1a21f8a1 smartwatt's version has been bumped to 0.7.0, but there is no associated tag.

This makes it difficult to install it in a stable way (e.g. when building a docker image). As it's not published on pypi, I usually uses:

    pip install git+https://github.com/powerapi-ng/smartwatts-formula.git@v0.6.0   

Could you add the corresponding 0.7.0 tag ?

Besides, `setup.cfg` point to powerapi 0.10.0 but `requirements.txt` still has 0.9.3.

**Comment by PierreRust** [comment]
Unfortunately, Smartwatt v0.6.0 uses powerapi v0.8.1 (declared in setup.cfg), which is rather old and lacks features we need.
In order to get a more recent version of powerapi  I need to use a more recent version of smartwatt and v0.7.0 is the only version since v0.6.0.

To avoid or at least mitigate this kind of issues, I would suggest to either
* use the same version number for powerAPI and smartwatt and bump it at the same time in both projects
* declare a range of powerapi's version smartwatt depends on : currently a version of smartwatt point to a single version of powerapi ( meaning that all the intermediate version of powerapi are never used if we respect the dependency declared in setup.cfg)

Imho the first approach would be much easier to implement and probably enough in our case.

**Comment by altor** [comment]
Hello, we create the tag and publish the release.

We will use your first approach for the next release

**Comment by PierreRust** [comment]
Great, thanks !
