### ISSUE TITLE
Smartwatts doesn't report per socket power usage (and its slow to read values from source/report power usage)

### ISSUE THREAD

**Issue by jorgermurillo** [powerapi-ng/smartwatts-formula#13]
This isn't actually an issue, but more of a question. I just built a Docker image using the most recent commit in the `pre-release` branch ( https://github.com/powerapi-ng/smartwatts-formula/commit/802d8c9c7d8048db825cf4087fde66dddc8fd1df ), and I see that in the output to influxdb2.0 and the csv files, there is no socket information. I used to deploy the image hosted on Docker Hub, and that one used to report per socket power consumption.

I just wanted to confirm that this was a change done intentionally instead of a bug.

Thank you!

**Comment by jorgermurillo** [comment]
Also, when using the `pre-release` branch it it super slow. The MongoDB Collection that stores the sensor readings keeps growing and there is a lag of minutes of the data outputed by the formula (which keeps growing!)

**Comment by MadalinaDinga** [comment]
Hi @jorgermurillo ! Have you been able to find a fix for the performance issues? My setups is similar to yours and I am running into the same problem (high power usage reporting delay).

**Comment by gfieni** [comment]
Hello,
There shouldn't have performance issues in the `2.1.0` version of SmartWatts.
Please open a new issue if you encounter other performance problems.
