### ISSUE TITLE
Dram formula can't be runned 

### ISSUE THREAD

**Issue by ldesauw** [powerapi-ng/smartwatts-formula#20]
When running smartwatts with the dram formula there is the following error : 
`AttributeError: Can't pickle local object 'setup_dram_formula_actor.<locals>.<lambda>'` 

The error should comme from the dispatch rule of the dram formula  in the main.py

**Comment by PierreRustOrange** [comment]
I also saw this last week, sorry I should have pushed a pushed a PR fixing that.
I can do it this afternoon if you want.
