### ISSUE TITLE
`smartwatts_install.sh` fails to install smartwatts `.deb` file

### ISSUE THREAD

**Issue by trahay** [powerapi-ng/smartwatts-formula#23]
When running `smartwatts_install.sh` and selecting the `.deb` installation mode, the installation script fails:
```
$ bash ./smartwatts_install.sh 
How do you want to install Smartwatts ?
1) pip 2) docker 3) deb
3
Installing Smartwatts...
Getting Smartwatts...
Smartwatts downloaded
Building...
Lecture des listes de paquets... Fait
E: Le fichier donné ./python3-rapl-smartwatts_*-1_all.deb n'est pas compris sur la ligne de commande
rm: impossible de supprimer 'python3-rapl-smartwatts_*-1_all.deb': Aucun fichier ou dossier de ce type
```

The problem comes from the filename of the .deb file: the downloaded file is named `python3-smartwatts_0.9.0-1_all.deb` and the script tries to install `python3-rapl-smartwatts_*-1_all.deb`.

**Comment by ldesauw** [comment]
[ed0ed](https://github.com/powerapi-ng/powerapi-ng.github.io/commit/ed0edbaf29371a1b5aa94bc7ddeac6c8817168b4) resolve the issue.
