### ISSUE TITLE
Save the results to prometheus db

### ISSUE THREAD

**Issue by marceloamaral** [powerapi-ng/smartwatts-formula#25]
Although the [documentation](https://powerapi-ng.github.io/database.html#prometheus) says that smartwatts can save the results into prometheus, it is not clear how to configure it.

Does it requires prometheus pushgateway?
Or will smartwatts start to expose metrics to be scraped?

I configured smartwatts to save the results to prometheus, as the documentation suggest, but I do not see any metric...
```
      "output": {
        "pusher_power": {
          "type": "prom",
          "uri": "http://prometheus-kube-prometheus-prometheus.monitoring",
          "port": 9090,
          "metric_name": "energy",
          "metric_description": "energy consumption"
        }
      },
```

**Comment by roda82** [comment]
Hello, 
No it  does not require prometheus pushgateway. Your second guess is wright. Smartwatts will expose metrics via an http server to be scraped. Therefore, you need to configure prometheus (via static_configs)  by using the uri and port that you define in the formula configuration. Therefore there is an error in the documentation. I will fix it.
