### ISSUE TITLE
`sender_name` is null

### ISSUE THREAD

**Issue by Alystrasz** [powerapi-ng/smartwatts-formula#33]
While using SmartWatts formula with HWPC sensor, data are correctly stored into mongodb, but while viewing data with MongoDB Compass, `sender_name` attribute is null.

![image](https://user-images.githubusercontent.com/11993538/227892456-d967cc81-cc0e-4b5b-a1c2-12074371a12e.png)

I used Docker images for HWPC, SmartWatts and mongodb.

###### HWPC

```json
{
  "name": "sensor",
  "verbose": true,
  "frequency": 500,
  "output": {
    "type": "mongodb",
    "uri": "mongodb://127.0.0.1",
    "database": "db_sensor",
    "collection": "report_0"
  },
  "system": {
    "rapl": {
      "events": ["RAPL_ENERGY_PKG"],
      "monitoring_type": "MONITOR_ONE_CPU_PER_SOCKET"
    },
    "msr": {
      "events": ["TSC", "APERF", "MPERF"]
    }
  },
  "container": {
    "core": {
      "events": [
        "CPU_CLK_THREAD_UNHALTED:REF_P",
        "CPU_CLK_THREAD_UNHALTED:THREAD_P",
        "LLC_MISSES",
        "INSTRUCTIONS_RETIRED"
      ]
    }
  }
}
```

###### SmartWatts

```json
{
  "verbose": true,
  "stream": true,
  "input": {
    "puller": {
      "model": "HWPCReport",
      "type": "mongodb",
      "uri": "mongodb://127.0.0.1",
      "db": "db_sensor",
      "collection": "report_0"
    }
  },
  "output": {
    "pusher_power": {
      "type": "mongodb",
      "uri": "mongodb://127.0.0.1",
      "db": "test_results",
      "collection": "power_consumption2"
    }
  },
  "cpu-frequency-base": 19,
  "cpu-frequency-min": 4,
  "cpu-frequency-max": 42,
  "cpu-error-threshold": 2.0,
  "disable-dram-formula": true,
  "sensor-report-sampling-interval": 1000
}
```

**Comment by gfieni** [comment]
Hello,

In SmartWatts configuration file, there is no `model` specified for the `puser_power` and the default output will be the internal PowerAPI actors message format, which is not intended for this use case.

Please add `"model": "PowerReport"` to the `output.pusher_power` section of SmartWatts configuration file to have your measurements in a more usable format.

**Comment by Alystrasz** [comment]
Adding the `"model": "PowerReport"` entry to the SmartWatts configuration has no effect.

I use latest SmartWatts image (digest: 0b7125b8c110ab8b89be43aae65dc30f5f8a0b18d189a25461485b3e3c6eac14).

**Comment by gfieni** [comment]
Thanks for you response.
There is indeed a problem in PowerAPI.
We will issue a fix and get back to you.

**Comment by roda82** [comment]
Hi, 
Thank you for the feedback. This big is relate to https://github.com/powerapi-ng/powerapi/issues/149 and therefore has been fixed. 

Regards,
