### ISSUE TITLE
Is the power-consumption output wrong ?

### ISSUE THREAD

**Issue by lkrumpak** [powerapi-ng/smartwatts-formula#52]
Hi guys,

I have deployed the sensor and smartwatts-formula in docker and I wish to measure the power-consumption of my kubernetes pods. However, as demonstrated in the image below I have ran my small application for a few minutes and I have cpu stressed one of the pods. 

After a few minutes of running, the pods return to an idle state. However, this transition doesn't seem to be registered by smartwatts. 

Do you know why this might be?

If I redeploy the sensor and smartwatts-formula, I seem to get more reasonable data with regards to the power consumption. 

FYI: The application used is [muBench](https://github.com/mSvcBench/muBench)

<img width="753" alt="image" src="https://github.com/powerapi-ng/smartwatts-formula/assets/32241461/17ebea4d-a007-4c69-af6b-8f8b4feb87f1">

**Comment by MaxiStefan** [comment]
Hi, I've also encountered slightly similar issues recently. Do you know anything about it @gfieni @roda82 ? Thanks in advance!

**Comment by gfieni** [comment]
Hello,
I am not able to reproduce this problem with SmartWatts v2.1.1 running on a server with an `Intel Xeon Gold 6130` CPU.
Can you give me the CPU model, the version of SmartWatts that you are using and the configuration file / cli flags used ?

Thanks.

**Comment by roda82** [comment]
Hello, 
In order to help you, @lkrumpak can you please provide us the information asked by @gfieni ? 

Regards,

**Comment by roda82** [comment]
Hello, 
Thank you for your feed back. So far we have not been able to reproduce the problem. Can you give us more details associated with your installation (OS version and kernel version)?

Regards,
