### ISSUE TITLE
predict in power report leads to error on InfluxDB

### ISSUE THREAD

**Issue by PierreRust** [powerapi-ng/smartwatts-formula#7]
Since commit 324bfdece5a0eff23fc4a8560fda9dd0895df72b a new `predict` entry has been added to the metadata of the PowerReport.

However, when saving the report to InfluxDB, the predict is stored as a tag (see `PowerModel.to_influxdb` ), which works for a while, until we have too many different values for the predict and get an `max-values-per-tag limit exceeded` error from InfluxDB. 
The problem is that **tag** are meant for storing data with a limited set of possible values, while `predict` is a float converted to a string and should thus be stored as a **field**.

The same problem occurred a few month ago with `ratio` and had been fixed in on PowerAPI side, with commit  powerapi-ng/powerapi@415bd05e19d81a4abced1e30e7faa8bda3e19e0d

I can easily propose a fix like the one made for ratio but, as we can see, the fix for ratio is quite brittle (a specific test in powerapi for something happening in the formula) ; is there any reason to include ratio and predict in the report's metadata ? couldn't we put these fields it directly in the report, like power ?

**Comment by PierreRustOrange** [comment]
By the way, the influxdb series also include `formula` as a tag, which is a hash such as : `a56245b14576471989f53789969f6af00ee009d1`.
This will eventually lead to the same issue when smartwatt has computed enough different formulas, although it will of course take longer.

**Comment by altor** [comment]
Hello, 
I make an update of PowerAPI
now, when storing `PowerReport` in influxDB, metadata are not stored.

If needed, the `PowerModel` class could be inherited to create a new class that store the wanted metadata in influxDB.
The instance of the `PowerModel` child class must be added to the `PusherGenerator` instance before generating pusher actors (see this [test](https://github.com/powerapi-ng/powerapi/blob/master/tests/integration/cli/test_generate_pusher.py) for an example )
