### ISSUE TITLE
Difference in powerapi version dependecy

### ISSUE THREAD

**Issue by PierreRustOrange** [powerapi-ng/smartwatts-formula#8]
This is more a question than a bug report : 

Smartwatt currently depends on powerapi version  0.6.11  (since commit d344416341a66cd8ea56ad8c2748280dd3f14352). Howerever, powerapi's current version is 0.7.3.
This means that we cannot use in smartwatt the last modifications introduced since 0.6.11 (sockerdb, etc, and the patch I propsed in #7 ).

Is there any reason for that ?

**Comment by altor** [comment]
Hello Pierre
a new release (`0.5.0`) is available, compatible with the last version of powerapi
