### ISSUE TITLE
Wrong dependecy to sklearn 0.17

### ISSUE THREAD

**Issue by PierreRust** [powerapi-ng/smartwatts-formula#9]
In setup.cfg, a dependency to sklearn is declared :
```
install_requires =
            powerapi [mongodb, influxdb, opentsdb, prometheus] == 0.9.0
            numpy>=1.14.0
            scipy>=0.17 
            sklearn>=0.17
```
However, there is no corresponding package on pypi : https://pypi.org/project/sklearn/ 

As a consequence, installing smartwatt with pip fails : 
```
>  pip install git+https://github.com/powerapi-ng/smartwatts-formula.git 
[...]
Collecting sklearn>=0.17 (from smartwatts==0.6.0)
ERROR: Could not find a version that satisfies the requirement sklearn>=0.17 (from smartwatts==0.6.0) (from versions: 0.0)
ERROR: No matching distribution found for sklearn>=0.17 (from smartwatts==0.6.0)

```

**Comment by PierreRust** [comment]
I guess that could be scikit-learn instead of sklearn, but the 0.17 version dates back from 2015, and it seems strange to specify a depency to such an old version given that is more than a dozen version version since that.

**Comment by gfieni** [comment]
This is now fixed.
Thanks for reporting this problem.

**Comment by PierreRust** [comment]
Thanks for the quick answer and fix ! :)
